### ISSUE TITLE
Initial publication

### ISSUE THREAD

**Issue by rgrempel** [Gizra/elm-essentials#1]
Basically, what I've started doing here is going through the various Gizra Elm projects and pulling out those things which are:

- generally useful
- not too specific to the project
- not part of some coherent whole that would be a useful package of its own

So, the idea would be that this could be a package that includes a whole bunch of little, useful things that would be a pain to maintain separately. Then, we'd delete stuff from existing projects and include this instead.

I have a few ideas for more focused packages already, so there are some things I'm already not putting in here.

- Anything that is specifically Drupal-related could go in a different package, I think.
- Anything that is Semantic UI related could go in a different package.

The general plan is to publish this, and then keep noodling away at it as time permits ... going through the various Gizra projects, adding stuff here, removing it from the projects, and so on.

Before actually publishing this for the first time, there are a few things we should think about:

## The name

Is `elm-essentials` a good name? I guess I like it. One alternative I considered was something like `gizra-elm-extras` -- but when you install it, you'd install it as:

    elm-package install Gizra/elm-essentials

... anyway, so it seems redundant to put "gizra-" in the name of the package as well.

## The namespace

In our internal projects, these are typically things in the `Utils` namespace. But, for public consumption, I thought it might be best to use a `Gizra` namespace -- it would seem a bit presumptuous to claim `Utils.Json` as a module name, for instance. (And module names aren't automatically namespaced in Elm like package names are, so it is important to avoid collisions with other packages).

## Is this a good idea at all?

I suppose there are a couple of alternatives to this kind of package.

- Just don't do it.
   
   But, I think it would be nice to be able to "install" a bunch of often-used code at once, rather than copying files into new projects.

- Immediately publish more focused packages.

   Of course, we do have many more focused packages, but I think there would be nice role for one more general package that can bring together a bunch of "little stuff". Otherwise, we could end up with a dozen (or more) packages that each have very little in them. But, as we notice more substantial, focused things here, we could break them out into packages of their own.

- Try to get these functions into existing "extras-style" packages

   Well, that might not be a bad idea. I suppose I'm just wondering whether that might be an unwieldy process, given how much common code we've got that would fit here. Perhaps that could also be something we do gradually -- that is, gradually find homes for some of these functions in the "extras" packages that other people maintain.

**Comment by amitaibu** [comment]
I love it! Kind of reminds me of http://package.elm-lang.org/packages/krisajenkins/elm-exts/latest which ended up also with smaller packages (e.g. RemoteData)

> The general plan is to publish this, and then keep noodling away at it as time permits ... going through the various Gizra projects, adding stuff here, removing it from the projects, and so on.

Yeah, some parts can defiantly find their way in the original/ extra package.

> The namespace

I think `Gizra/foo` is good enough. Like we have in NRI's [package](http://package.elm-lang.org/packages/NoRedInk/view-extra/2.0.0/View-Extra) (btw, look at this package -- our Html stuff could move there, as they have a lazy loaded approach to the funtions, such as `viewIf`)

**Comment by rgrempel** [comment]
krisajenkins/elm-exts has a lot of neat stuff in it -- I'll take a closer look at that (and the NRI things)!

**Comment by rgrempel** [comment]
BTW, thanks for pointing out elm-doc-test to me -- that is really delightful!
