### ISSUE TITLE
Add Endpoints

### ISSUE THREAD

**Issue by amitaibu** [Gizra/elm-essentials#2]
This is my adaptation of your intial Endpoints. The bigget change AFAIK is that the create encoder maybe different from the existing entities.

I don't think it deserves own module, since the Endpoints have some assumptions about the endpoints, which are Drupal RESTful specific (and I don't think it's worth the effort now to try and generalize it)

**Comment by amitaibu** [comment]
I've also changed `get`/ `get404`, `patch` to return only `Result error value` -- without the key, as we already have it

**Comment by rgrempel** [comment]
Ah, I had started https://github.com/Gizra/elm-restful for the endpoints and a few other things. Even if it has some Drupal-specific elements at the moment, I think it is perhaps a sufficiently distinct subject-matter to have its own package?

In any event, I will integrate your modifications -- the separate `create` type is a great idea.

**Comment by rgrempel** [comment]
This is being done on https://github.com/Gizra/elm-restful/pull/2
